version: 2.4.11.{Build}

environment:
  matrix:
  - PlatformToolset: v142
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019

  - PlatformToolset: v141_xp
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017


platform:
    - x64
    - Win32

configuration:
    - Release
    - Debug

install:
    - if "%platform%"=="x64" set platform_input=x64
    - if "%platform%"=="Win32" set platform_input=Win32
    - if "%platform%"=="x64" set archi=amd64
    - if "%platform%"=="Win32" set archi=x86
    - if "%PlatformToolset%"=="v141_xp" call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" %archi%
    - if "%PlatformToolset%"=="v142" call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" %archi%

    - if "%platform_input%"=="Win32" cd "%APPVEYOR_BUILD_FOLDER%"\libs\libxml\x86
    - if "%platform_input%"=="Win32" 7z x -y libxml2-2.9.3-win32-x86.7z > nul
    - if "%platform_input%"=="Win32" 7z x -y iconv-1.14-win32-x86.7z > nul
    - if "%platform_input%"=="Win32" 7z x -y libxslt-1.1.28-win32-x86.7z > nul

    - if "%platform_input%"=="x64" cd "%APPVEYOR_BUILD_FOLDER%"\libs\libxml\x64
    - if "%platform_input%"=="x64" 7z x -y libxml2-2.9.3-win32-x86_64.7z > nul
    - if "%platform_input%"=="x64" 7z x -y iconv-1.14-win32-x86_64.7z > nul
    - if "%platform_input%"=="x64" 7z x -y libxslt-1.1.28-win32-x86_64.7z > nul


build_script:
    - cd "%APPVEYOR_BUILD_FOLDER%"
    - msbuild XMLTools.sln /m /p:configuration="%configuration%" /p:platform="%platform_input%" /p:PlatformToolset="%PlatformToolset%" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

after_build:
    - cd "%APPVEYOR_BUILD_FOLDER%"
    - ps: |
        Push-AppveyorArtifact "$env:PLATFORM_INPUT\$env:CONFIGURATION\XMLTools.dll" -FileName XMLTools.dll
        if ($($env:APPVEYOR_REPO_TAG) -eq "true" -and $env:CONFIGURATION -eq "Release" -and $env:PLATFORMTOOLSET -eq "v141_xp")
        {
            if($env:ARCH -eq "x64"){
                $ZipFileName = "XMLTools_$($env:APPVEYOR_REPO_TAG_NAME)_x64.zip"
                7z a $ZipFileName $env:APPVEYOR_BUILD_FOLDER\$env:PLATFORM_INPUT\$env:CONFIGURATION\XMLTools.dll
                #TODO add further dependencies and txt files
            }
            if($env:ARCH -eq "Win32"){
                $ZipFileName = "XMLTools_$($env:APPVEYOR_REPO_TAG_NAME)_x86.zip"
                7z a $ZipFileName $env:APPVEYOR_BUILD_FOLDER\$env:PLATFORM_INPUT\$env:CONFIGURATION\XMLTools.dll
                #TODO add further dependencies and txt files
            }
        }
artifacts:
  - path: XMLTools_*.zip
    name: releases

deploy:
    provider: GitHub
    description: ''
    auth_token:
        secure: !!!TODO!!!
    artifact: releases
    draft: false
    prerelease: false
    force_update: true
    on:
        appveyor_repo_tag: true
        PlatformToolset: v141_xp
        configuration: Release
